### ISSUE TITLE
Unable to setup

### ISSUE THREAD

**Issue by Rong-Tao** [google-research/recsim#1]
After downloading the zip and runsetup.py in the recsim-master folder.
Following error occurred
//////////////////////////////////////////////////////////////////////////////////////
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
//////////////////////////////////////////////////////////////////////////////////////
 Then I tried to install it myself.

///////////////////////////////////
(tf_gpu) C:\Users\TR201\recsim>python -m pip install recsim
Requirement already satisfied: recsim in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (0.1.6)
Requirement already satisfied: gin-config in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from recsim) (0.2.1)
Requirement already satisfied: gym in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from recsim) (0.14.0)
Requirement already satisfied: atari-py in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from recsim) (0.2.6)
Requirement already satisfied: dopamine-rl in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from recsim) (2.0.5)
Requirement already satisfied: numpy in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from recsim) (1.16.4)
Requirement already satisfied: tensorflow in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from recsim) (1.13.1)
Requirement already satisfied: absl-py in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from recsim) (0.7.1)
Requirement already satisfied: six>=1.10.0 in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from gin-config->recsim) (1.12.0)
Requirement already satisfied: scipy in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from gym->recsim) (1.3.0)
Requirement already satisfied: cloudpickle~=1.2.0 in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from gym->recsim) (1.2.2)
Requirement already satisfied: pyglet<=1.3.2,>=1.2.0 in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from gym->recsim) (1.3.2)
Requirement already satisfied: opencv-python>=3.4.1.15 in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from dopamine-rl->recsim) (4.1.1.26)
Requirement already satisfied: tensorboard<1.14.0,>=1.13.0 in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from tensorflow->recsim) (1.13.1)
Requirement already satisfied: keras-applications>=1.0.6 in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from tensorflow->recsim) (1.0.8)
Requirement already satisfied: tensorflow-estimator<1.14.0rc0,>=1.13.0 in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from tensorflow->recsim) (1.13.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from tensorflow->recsim) (1.1.0)
Requirement already satisfied: wheel>=0.26 in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from tensorflow->recsim) (0.33.4)
Requirement already satisfied: gast>=0.2.0 in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from tensorflow->recsim) (0.2.2)
Requirement already satisfied: grpcio>=1.8.6 in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from tensorflow->recsim) (1.16.1)
Requirement already satisfied: keras-preprocessing>=1.0.5 in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from tensorflow->recsim) (1.1.0)
Requirement already satisfied: astor>=0.6.0 in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from tensorflow->recsim) (0.7.1)
Requirement already satisfied: protobuf>=3.6.1 in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from tensorflow->recsim) (3.8.0)
Requirement already satisfied: future in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from pyglet<=1.3.2,>=1.2.0->gym->recsim) (0.17.1)
Requirement already satisfied: werkzeug>=0.11.15 in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from tensorboard<1.14.0,>=1.13.0->tensorflow->recsim) (0.15.4)
Requirement already satisfied: markdown>=2.6.8 in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from tensorboard<1.14.0,>=1.13.0->tensorflow->recsim) (3.1.1)
Requirement already satisfied: h5py in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from keras-applications>=1.0.6->tensorflow->recsim) (2.9.0)
Requirement already satisfied: setuptools in c:\users\tr201\anaconda3\envs\tf_gpu\lib\site-packages (from protobuf>=3.6.1->tensorflow->recsim) (41.0.1)

(tf_gpu) C:\Users\TR201\recsim>python setup.py
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

(tf_gpu) C:\Users\TR201\recsim>cd recsim

(tf_gpu) C:\Users\TR201\recsim\recsim>python main.py
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    from recsim.agents import full_slate_q_agent
  File "C:\Users\TR201\Anaconda3\envs\tf_gpu\lib\site-packages\recsim\agents\__init__.py", line 19, in <module>
    from recsim.agents import full_slate_q_agent
  File "C:\Users\TR201\Anaconda3\envs\tf_gpu\lib\site-packages\recsim\agents\full_slate_q_agent.py", line 22, in <module>
    from recsim.agents.dopamine import dqn_agent
  File "C:\Users\TR201\Anaconda3\envs\tf_gpu\lib\site-packages\recsim\agents\dopamine\dqn_agent.py", line 23, in <module>
    from dopamine.agents.dqn import dqn_agent
  File "C:\Users\TR201\Anaconda3\envs\tf_gpu\lib\site-packages\dopamine\agents\dqn\dqn_agent.py", line 28, in <module>
    from dopamine.discrete_domains import atari_lib
  File "C:\Users\TR201\Anaconda3\envs\tf_gpu\lib\site-packages\dopamine\discrete_domains\atari_lib.py", line 31, in <module>
    import atari_py
  File "C:\Users\TR201\Anaconda3\envs\tf_gpu\lib\site-packages\atari_py\__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "C:\Users\TR201\Anaconda3\envs\tf_gpu\lib\site-packages\atari_py\ale_python_interface.py", line 18, in <module>
    'ale_interface/ale_c.dll'))
  File "C:\Users\TR201\Anaconda3\envs\tf_gpu\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\TR201\Anaconda3\envs\tf_gpu\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] Can not find the module.
////////////////////////////////////////////////////////////////

please help

**Comment by cwhsu-google** [comment]
I believe [this atari-py problem](https://github.com/openai/gym/issues/1538) was fixed already. Could you install the newest version of atari-py (0.3.0 instead of 0.2.6)?

**Comment by Rong-Tao** [comment]
I installed the newest version of atari-py. Which does not solve the problem.

in C:\Users\TR201\Anaconda3\envs\tf_gpu\Lib\site-packages\atari_py-0.3.0-py3.7-win-amd64.egg\atari_py\ale_python_interface.py
Line 18 it requires that :
/////////////////////////////////////////////////////////////////////////////////////
    ale_lib = cdll.LoadLibrary(os.path.join(os.path.dirname(__file__),
                                            'ale_interface/ale_c.dll'))
///////////////////////////////////////////////////////////////////////////////////////
And I checked the ale_interface folder, where ale_c.dll is still missing
(The following folder)
https://github.com/openai/atari-py/tree/master/atari_py/ale_interface
///////////////////////////////////////////////////////////////////////////////////////
Could you please provide the download of the file "ale_c.dll"?

**Comment by cwhsu-google** [comment]
Sorry we meant to manually download atari-py and ale_c.dll using the following [link](https://files.pythonhosted.org/packages/df/c3/f70777c0a66fa8a26cbf471c4d96e304f5cf79718ea734880b4b36bc95fd/atari_py-0.2.6-cp37-cp37m-win_amd64.whl)
This has nothing to do with atari-py-0.3.0. You could try to remove the line
import atari_py
in File "C:\Users\TR201\Anaconda3\envs\tf_gpu\lib\site-packages\dopamine\discrete_domains\atari_lib.py" if you are not really using atar-py.
We closed this issue due to time out. Please reply back if you have this issue resolved.

**Comment by Rong-Tao** [comment]
I fix the ale.dll problem.,with this:
 https://github.com/openai/gym/issues/1726#event-2777478554
///////////////////////////////////////////////////////////////////////////////////////////////
(tf_gpu) C:\Users\TR201\recsim\recsim>python main.py --logtostderr
WARNING:tensorflow:From C:\Users\TR201\Anaconda3\envs\tf_gpu\lib\site-packages\dopamine_rl-3.0.0-py3.7.egg\dopamine\agents\dqn\dqn_agent.py:97: The name tf.train.RMSPropOptimizer is deprecated. Please use tf.compat.v1.train.RMSPropOptimizer instead.

FATAL Flags parsing error: flag --base_dir=None: Flag --base_dir must have a value other than None.
Pass --helpshort or --helpfull to see help on flags.
//////////////////////////////////////////////////////////////////////////////////////////////////
still could not run the test code

**Comment by cwhsu-google** [comment]
Glad that the ald_c.dll problem got fixed. You have to set the flag
base_dir to some directory. Please see the example usage in README.

python main.py --logtostderr \
  --base_dir="/tmp/recsim/interest_exploration_full_slate_q" \
  --agent_name=full_slate_q \
  --environment_name=interest_exploration \
  --episode_log_file='episode_logs.tfrecord' \
  --gin_bindings=simulator.runner_lib.Runner.max_steps_per_episode=100 \
  --gin_bindings=simulator.runner_lib.TrainRunner.num_iterations=10 \
  --gin_bindings=simulator.runner_lib.TrainRunner.max_training_steps=100 \
  --gin_bindings=simulator.runner_lib.EvalRunner.max_eval_episodes=5

**Comment by cwhsu-google** [comment]
Closing this issue due to time out. Please reply back if you have this issue resolved.
