### ISSUE TITLE
Support for interleaved user interaction

### ISSUE THREAD

**Issue by jeremy1320** [google-research/recsim#12]
Hi,
On page 12 of the white paper refers that "In the current design, the simulator sequentially simulates each user."
Is it available to support interleaved user interaction now?

Thanks,
Jeremy.

**Comment by cwhsu-google** [comment]
Yes. We implemented a MultiUserEnvironment
<https://github.com/google-research/recsim/blob/master/recsim/simulator/environment.py#L225>
class
which simulates a batch of users every step. Do you want to take a look and
give it a try? Thanks for using RecSim.
