### ISSUE TITLE
Accuracy and Diversity

### ISSUE THREAD

**Issue by vahidbaghi** [google-research/recsim#13]
Hi, on page 13 of the white paper refers that :

> RECSIM includes a number of typical metrics (e.g., average cumulative
reward and episode length) as well as some basic diversity metrics.

Is there an example for calculating such metrics (i.e., **accuracy** and **diversity**)?
Thanks.

**Comment by cwhsu-google** [comment]
You can take a look on
https://github.com/google-research/recsim/blob/master/recsim/utils.py for
an example slicing engagement metrics by video clusters. The code about
cumulative reward and episode length is in
https://github.com/google-research/recsim/blob/master/recsim/simulator/runner_lib.py#L300.
Thanks for using RecSim.
