### ISSUE TITLE
Problem in tfnightly and dopamine

### ISSUE THREAD

**Issue by joeppereira** [google-research/recsim#14]

**Comment by joeppereira** [comment]
ModuleNotFoundError: No module named 'tensorflow.contrib'

This error occurs if you try multiple variations

**Comment by cwhsu-google** [comment]
Thank you for using RecSim. Not sure if this is related to
https://github.com/google-research/recsim/issues/9 as RecSim itself doesn't
use anything from tensorflow.contrib. Could you provide the stack trace and
system information for further debugging?
