### ISSUE TITLE
Minor bug in slate_decomp_q_agent

### ISSUE THREAD

**Issue by ShishirKumar93** [google-research/recsim#17]
I was training a slate_decomp_q_agent and ran into this AttributeError related to tf.compat.v1 module. Please refer to [this](https://github.com/collinprather/SlateQ/blob/354325f376367abcb8e1e6b7003c54465d3bc89b/notebooks/SlateQ_comparison.ipynb) notebook for more details.

`AttributeError: module 'tensorflow._api.v1.compat.v1.compat' has no attribute 'v1'`

L22 In the slate_decomp_q_agent.py:
`import tensorflow.compat.v1 as tf`

L175 in the same file:
`output_slate = tf.compat.v1.where(tf.equal(mask, 0))`

I changed L175 (and other such instances) to:
`output_slate = tf.where(tf.equal(mask, 0))`

And it worked like a charm. If you think that's the right approach, I can submit a pull request for the same.

FYI, this is the first time I am opening an issue. If there's anything else you need from my side, feel free to comment.

My env details:

```
# OS: macOS Mojave v10.14.6
# used pip virtual environments with below libraries installed
absl-py==0.9.0
appnope==0.1.0
astor==0.8.1
astunparse==1.6.3
attrs==19.3.0
backcall==0.2.0
bleach==3.1.5
cachetools==4.1.0
certifi==2020.4.5.2
chardet==3.0.4
cloudpickle==1.3.0
decorator==4.4.2
defusedxml==0.6.0
dopamine-rl==3.0.1
entrypoints==0.3
future==0.18.2
gast==0.2.2
gin-config==0.3.0
google-auth==1.16.1
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.29.0
gym==0.17.2
h5py==2.10.0
idna==2.9
importlib-metadata==1.6.1
ipykernel==5.3.0
ipython==7.15.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.17.0
Jinja2==2.11.2
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.3
jupyter-console==6.1.0
jupyter-core==4.6.3
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
Markdown==3.2.2
MarkupSafe==1.1.1
mistune==0.8.4
nbconvert==5.6.1
nbformat==5.0.7
notebook==6.0.3
numpy==1.18.5
oauthlib==3.1.0
opencv-python==4.2.0.34
opt-einsum==3.2.1
packaging==20.4
pandocfilters==1.4.2
parso==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.1.2
prometheus-client==0.8.0
prompt-toolkit==3.0.5
protobuf==3.12.2
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyglet==1.5.0
Pygments==2.6.1
pyparsing==2.4.7
pyrsistent==0.16.0
python-dateutil==2.8.1
pyzmq==19.0.1
qtconsole==4.7.4
QtPy==1.9.0
recsim==0.2.3
requests==2.23.0
requests-oauthlib==1.3.0
rsa==4.0
scipy==1.4.1
Send2Trash==1.5.0
six==1.15.0
tensorboard==1.15.0
tensorboard-plugin-wit==1.6.0.post3
tensorflow==1.15.0
tensorflow-estimator==1.15.1
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
tornado==6.0.4
traitlets==4.3.3
urllib3==1.25.9
wcwidth==0.2.4
webencodings==0.5.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
wrapt==1.12.1
zipp==3.1.0

```

**Comment by cwhsu-google** [comment]
Thanks for raising this problem. Please check the latest version of RecSim and we should already fix this problem by replacing tf.compat.v1 with tf there. Let me know if you still have issues.
