### ISSUE TITLE
pip error

### ISSUE THREAD

**Issue by Bilwang129** [google-research/recsim#2]
when I run `pip install recsim` to install the `recsim`,following error occurred:
 

> ERROR: Could not find a version that satisfies the requirement dopamine-rl>=2.0.6 (from recsim) (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5)

> ERROR: No matching distribution found for dopamine-rl>=2.0.6 (from recsim)

**Comment by pkorobov** [comment]
You should at first install the latest dopamine version from their repository with some command like
`pip install git+https://github.com/google/dopamine.git`
Currently it is 3.0.0.

**Comment by cwhsu-google** [comment]
Thanks for using RecSim. As said, you want to install the latest version of
Dopamine from GitHub. The latest version of Dopamine on PyPI is still 2.0.5
https://pypi.org/project/dopamine-rl/

**Comment by TobyGE** [comment]
> You should at first install the latest (as I did) dopamine version from their repository with some command like `pip install git+https://github.com/google/dopamine.git`.
> Currently it is 3.0.0.

It's helpful
