### ISSUE TITLE
Q&A

### ISSUE THREAD

**Issue by ghzha0** [google-research/recsim#20]
How can I evaluate whether the simulator is valuable or not?
I mean, are there any metrics which can evaluate the performance of different simulators?

**Comment by cwhsu-google** [comment]
Thanks for using RecSim. Are you talking about evaluating different
recommender agents? If so, RecSim includes a number of typical metrics
(e.g., average cumulative reward and episode length) as well as some basic
diversity metrics. You can define your reward function (like
total_clicks_reward in
https://github.com/google-research/recsim/blob/master/recsim/environments/interest_exploration.py#L401)
and RecSim can visualize the metrics over time.

**Comment by cwhsu-google** [comment]
Closing thing issue for now and let me know if you have any questions.
