### ISSUE TITLE
recism requires dopamine-rl>=2.0.6, which is not in PyPI

### ISSUE THREAD

**Issue by wesbarnett** [google-research/recsim#8]
### Summary

Running `pip install recsim` fails due to dependency on `dopamine-rl>=2.0.6`, which is not in PyPI.

### Description

Run the following:

```
pip install recsim
```

The following is then output:
```
Collecting dopamine-rl>=2.0.6 (from recsim)
  ERROR: Could not find a version that satisfies the requirement dopamine-rl>=2.0.6 (from recsim) (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5)
ERROR: No matching distribution found for dopamine-rl>=2.0.6 (from recsim)
```

I don't see `dopamine-rl>=2.06` [in PyPI](https://pypi.org/project/dopamine-rl/#history).

**Comment by wesbarnett** [comment]
Looks like this is a duplicate of #2. Regardless, the documentation states one simply needs to do `pip install recsim`, but one must first install `dopamine-rl` from their git repository.

**Comment by mmladenov-google** [comment]
Thanks for catching this! We'll update the documentation to avoid confusion in the short term util the issue resolves itself.
